version: "3"
services:
    account:
        build:
            context: .
            dockerfile: Dockerfile.account.dev
        ports:
            - 8762:8762
#ss



    



        


            


